spring.application.name=Reponyx

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/reponyx}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GOOGLE_GENAI_EMBEDDING_API_KEY}
